name: connector_app
dependencies:
  browser: ^0.10.0+2
  polymer: ^1.0.0-rc.15
  polymer_elements: ^1.0.0-rc.8
  web_components: ^0.12.3
  source_gen: ^0.5.0+1
  http: ^0.11.0
  yaml: ^2.1.0
  rxdart: ^0.3.20
  autonotify_observe: any
  observe: any
dev_dependencies:
  build: ^0.3.0+1
transformers:
  - autonotify_observe
  - polymer:
      entry_points: web/index.html
