# This is currently how the app is configured to test different connectors
# When the app is deployed to an environment i.e. foo.com/ this value should
# be updated.
core_host: http://localhost:9000/
username: N00194830
